name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2023-10-02"
machine_id: 1

log:
  level: "debug"
  filename: "bluebell"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "240091"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
#  max_life_time: time.Hour

redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  password: ""
  pool_size: 100